version: '3.1'

services:
   db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mbit
      MYSQL_USER: mbit
      MYSQL_DATABASE: Pictures
   
   api:
    build: api
    ports:
      - 80:80

   volumes:
    - ./database:/var/lib/mysql
    - ./images_db:/app/images_db